name: ci

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev/staging/prod)'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN }}
  
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build frontend
        run: docker build -t frontend:latest ./app/frontend

      - name: build backend
        run: docker build -t backend:latest ./app/backend

      - name: Scan Backend Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: backend:latest
          format: table
          exit-code: 0
          ignore-unfixed: true

      - name: Trivy Scan (Save Report)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: backend:latest
          format: json
          output: trivy-reportbackend.json    

      - name: Scan Frontend Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: frontend:latest
          format: table
          exit-code: 0
          ignore-unfixed: true  

      - name: Trivy Scan (Save Report)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: frontend:latest
          format: json
          output: trivy-reportfrontend.json

      - name: Install Snyk
        run: npm install -g snyk
    
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Install Backend Dependencies
        run: pip install -r requirements.txt
        working-directory: app/backend
      
      - name: Snyk Test Backend
        run: snyk test || true
        working-directory: app/backend

      - name: Snyk Test Frontend
        run: snyk test || true
        working-directory: app/frontend

      - name: Snyk Scan Backend Image
        run: snyk container test backend:latest || true

      - name: Snyk Scan Frontend Image
        run: snyk container test frontend:latest || true
   
      - name: push frontend
        run: |
         docker tag frontend:latest ${{ secrets.DOCKER_USERNAME }}/frontend:latest
         docker push ${{secrets.DOCKER_USERNAME}}/frontend:latest

      - name: push backend
        run: |
         docker tag backend:latest ${{ secrets.DOCKER_USERNAME }}/backend:latest 
         docker push ${{secrets.DOCKER_USERNAME}}/backend:latest
 
  infrastructure:
    needs: build
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Environment Variable
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
      - name: set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::179832230574:role/oidc-2
          aws-region: ap-south-1

      - name: Set Environment Config
        run: |
          if [ "${{ github.event.inputs.environment }}" = "staging" ]; then
           echo INSTANCE_TYPE="c7i-medium" >> $GITHUB_ENV
          else
           echo INSTANCE_TYPE="t2.micro" >> $GITHUB_ENV
          fi
        
      - name: terraform init
        run: terraform init
        working-directory: terraform-files
    
      - name: terraform validate
        run: terraform validate
        working-directory: terraform-files
    
      - name: terraform plan
        run: |
          terraform plan \
            -var="instance_type=${{ env.INSTANCE_TYPE }}" \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -out=tfplan
        working-directory: terraform-files
    
      - name: terraform apply
        run: |
          terraform apply \
            -var="instance_type=${{ env.INSTANCE_TYPE }}" \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -auto-approve tfplan
        working-directory: terraform-files

      - name: Get Terraform Outputs
        id: tf_outputs
        run: |
          echo "frontend_ip=$(terraform output -raw aws_instance_public_ip)" >> $GITHUB_OUTPUT
          echo "backend_ip=$(terraform output -raw aws_instance_private_ip)" >> $GITHUB_OUTPUT
        working-directory: terraform-files

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ steps.tf_outputs.outputs.frontend_ip }}   # public EC2
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
           echo "Connected to Frontend EC2"
           echo "${{ secrets.EC2_SSH_KEY }}" > flask.pem
           chmod 400 flask.pem

           ssh -i flask.pem -o StrictHostKeyChecking=no ubuntu@${{ steps.tf_outputs.outputs.backend_ip }}
           echo "Connected to Backend EC2"

           docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
           docker stop backend || true
           docker rm backend || true
           docker run -d -p 5000:5000 --name backend ${{ secrets.DOCKER_USERNAME }}/backend:latest

           EOF

           docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
           docker stop frontend || true
           docker rm frontend || true
           docker run -d -p 80:80 --name frontend ${{ secrets.DOCKER_USERNAME }}/frontend:latest